kind: pipeline
type: docker
name: build

services:
- name: postgres
  image: postgres
  environment:
    POSTGRES_USER: timodb
    POSTGRES_PASSWORD: secret
    POSTGRES_DB: student-progress-test

concurrency:
  limit: 1

steps:
- name: test and build
  image: mcr.microsoft.com/dotnet/sdk:5.0-alpine
  commands:
    - dotnet restore
    - dotnet build
    - dotnet test
  environment:
    ConnectionStrings__Test:
      from_secret: connectionstringtest
    canvas__url:
      from_secret: canvasurl
    canvas__key:
      from_secret: canvaskey
  
      
---

kind: pipeline
type: ssh
name: deployment
depends_on:
  - build

server:
  host:
    from_secret: host
  user:
    from_secret: user
  password:
    from_secret: password

clone:
  disable: true

steps:
  - name: move
    commands:
    - cd /home/apper/projects/StudentProgress
    - git checkout main
    - git pull
    - docker-compose up -d --build

trigger:
  branch:
    - main
  event:
    - push