kind: pipeline
type: docker
name: build

concurrency:
  limit: 1

steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
  commands:
    - dotnet restore
    - dotnet build
  
- name: test 
  image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
  environment:
    ConnectionStrings__WebContext:
      from_secret: ConnectionStrings__WebContext
    ConnectionStrings__ProgressContext:
      from_secret: connectionstringtest
    canvas__url:
      from_secret: canvasurl
    canvas__key:
      from_secret: canvaskey
  commands:
    - dotnet test
      
- name: qa
  image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
  environment:
    sonarqube_host:
      from_secret: sonarqube_host
    sonarqube_token:
      from_secret: sonarqube_token
    sonarqube_project:
      from_secret: sonarqube_project
  commands:
    - apk add nodejs
    - export PATH=$PATH:/usr/bin/node
    - apk add openjdk17
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet tool install --global dotnet-sonarscanner
    - apk add libxml2
    - dotnet tool install --global dotnet-coverage
    - dotnet sonarscanner begin /k:"$sonarqube_project" /d:sonar.host.url="$sonarqube_host" /d:sonar.token="$sonarqube_token" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
    - dotnet build
    - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
    - dotnet sonarscanner end /d:sonar.token="$sonarqube_token"
---

kind: pipeline
type: ssh
name: deployment
depends_on:
  - build

server:
  host:
    from_secret: host
  user:
    from_secret: user
  password:
    from_secret: password

clone:
  disable: true

steps:
  - name: move
    commands:
    - cd /home/apper/projects/StudentProgress
    - git checkout main
    - git pull
    - docker-compose up -d --build

trigger:
  branch:
    - main
  event:
    - push